// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/time/v1/time_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentTimeRequest) Reset() {
	*x = GetCurrentTimeRequest{}
	mi := &file_api_time_v1_time_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentTimeRequest) ProtoMessage() {}

func (x *GetCurrentTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_time_v1_time_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentTimeRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentTimeRequest) Descriptor() ([]byte, []int) {
	return file_api_time_v1_time_service_proto_rawDescGZIP(), []int{0}
}

type GetCurrentTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentTime   string                 `protobuf:"bytes,1,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentTimeResponse) Reset() {
	*x = GetCurrentTimeResponse{}
	mi := &file_api_time_v1_time_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentTimeResponse) ProtoMessage() {}

func (x *GetCurrentTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_time_v1_time_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentTimeResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentTimeResponse) Descriptor() ([]byte, []int) {
	return file_api_time_v1_time_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentTimeResponse) GetCurrentTime() string {
	if x != nil {
		return x.CurrentTime
	}
	return ""
}

var File_api_time_v1_time_service_proto protoreflect.FileDescriptor

const file_api_time_v1_time_service_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/time/v1/time_service.proto\x12\x10smpl.api.time.v1\"\x17\n" +
	"\x15GetCurrentTimeRequest\";\n" +
	"\x16GetCurrentTimeResponse\x12!\n" +
	"\fcurrent_time\x18\x01 \x01(\tR\vcurrentTime2r\n" +
	"\vTimeService\x12c\n" +
	"\x0eGetCurrentTime\x12'.smpl.api.time.v1.GetCurrentTimeRequest\x1a(.smpl.api.time.v1.GetCurrentTimeResponseB1Z/github.com/kostyay/grpc-web-example/api/time/v1b\x06proto3"

var (
	file_api_time_v1_time_service_proto_rawDescOnce sync.Once
	file_api_time_v1_time_service_proto_rawDescData []byte
)

func file_api_time_v1_time_service_proto_rawDescGZIP() []byte {
	file_api_time_v1_time_service_proto_rawDescOnce.Do(func() {
		file_api_time_v1_time_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_time_v1_time_service_proto_rawDesc), len(file_api_time_v1_time_service_proto_rawDesc)))
	})
	return file_api_time_v1_time_service_proto_rawDescData
}

var file_api_time_v1_time_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_time_v1_time_service_proto_goTypes = []any{
	(*GetCurrentTimeRequest)(nil),  // 0: smpl.api.time.v1.GetCurrentTimeRequest
	(*GetCurrentTimeResponse)(nil), // 1: smpl.api.time.v1.GetCurrentTimeResponse
}
var file_api_time_v1_time_service_proto_depIdxs = []int32{
	0, // 0: smpl.api.time.v1.TimeService.GetCurrentTime:input_type -> smpl.api.time.v1.GetCurrentTimeRequest
	1, // 1: smpl.api.time.v1.TimeService.GetCurrentTime:output_type -> smpl.api.time.v1.GetCurrentTimeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_time_v1_time_service_proto_init() }
func file_api_time_v1_time_service_proto_init() {
	if File_api_time_v1_time_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_time_v1_time_service_proto_rawDesc), len(file_api_time_v1_time_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_time_v1_time_service_proto_goTypes,
		DependencyIndexes: file_api_time_v1_time_service_proto_depIdxs,
		MessageInfos:      file_api_time_v1_time_service_proto_msgTypes,
	}.Build()
	File_api_time_v1_time_service_proto = out.File
	file_api_time_v1_time_service_proto_goTypes = nil
	file_api_time_v1_time_service_proto_depIdxs = nil
}
