// @generated by protoc-gen-es v2.5.0 with parameter "target=ts"
// @generated from file api/time/v1/time_service.proto (package smpl.api.time.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/time/v1/time_service.proto.
 */
export const file_api_time_v1_time_service: GenFile = /*@__PURE__*/
  fileDesc("Ch5hcGkvdGltZS92MS90aW1lX3NlcnZpY2UucHJvdG8SEHNtcGwuYXBpLnRpbWUudjEiFwoVR2V0Q3VycmVudFRpbWVSZXF1ZXN0Ii4KFkdldEN1cnJlbnRUaW1lUmVzcG9uc2USFAoMY3VycmVudF90aW1lGAEgASgJMnIKC1RpbWVTZXJ2aWNlEmMKDkdldEN1cnJlbnRUaW1lEicuc21wbC5hcGkudGltZS52MS5HZXRDdXJyZW50VGltZVJlcXVlc3QaKC5zbXBsLmFwaS50aW1lLnYxLkdldEN1cnJlbnRUaW1lUmVzcG9uc2VCMVovZ2l0aHViLmNvbS9rb3N0eWF5L2dycGMtd2ViLWV4YW1wbGUvYXBpL3RpbWUvdjFiBnByb3RvMw");

/**
 * @generated from message smpl.api.time.v1.GetCurrentTimeRequest
 */
export type GetCurrentTimeRequest = Message<"smpl.api.time.v1.GetCurrentTimeRequest"> & {
};

/**
 * Describes the message smpl.api.time.v1.GetCurrentTimeRequest.
 * Use `create(GetCurrentTimeRequestSchema)` to create a new message.
 */
export const GetCurrentTimeRequestSchema: GenMessage<GetCurrentTimeRequest> = /*@__PURE__*/
  messageDesc(file_api_time_v1_time_service, 0);

/**
 * @generated from message smpl.api.time.v1.GetCurrentTimeResponse
 */
export type GetCurrentTimeResponse = Message<"smpl.api.time.v1.GetCurrentTimeResponse"> & {
  /**
   * @generated from field: string current_time = 1;
   */
  currentTime: string;
};

/**
 * Describes the message smpl.api.time.v1.GetCurrentTimeResponse.
 * Use `create(GetCurrentTimeResponseSchema)` to create a new message.
 */
export const GetCurrentTimeResponseSchema: GenMessage<GetCurrentTimeResponse> = /*@__PURE__*/
  messageDesc(file_api_time_v1_time_service, 1);

/**
 * @generated from service smpl.api.time.v1.TimeService
 */
export const TimeService: GenService<{
  /**
   * @generated from rpc smpl.api.time.v1.TimeService.GetCurrentTime
   */
  getCurrentTime: {
    methodKind: "unary";
    input: typeof GetCurrentTimeRequestSchema;
    output: typeof GetCurrentTimeResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_time_v1_time_service, 0);

